### PR TITLE
Update PHPUnit config description

### LINKED ISSUE #21: PHPUnit config description isn't up to date
PHPUnit 11.4 - resp. something before - removed the `include` element from `coverage`. Instead the `source` element has to be taken. Also the shown attributes of `coverage` were removed.

### PR DESCRIPTION
**Pull request by 1stthomas**
Should fix #21

### CODE REVIEW

**Comment by timkrase** [comment]
Thanks! Haven't used this in a while and wasn't aware of the changes in the structure. Seems like it was already the case in PHPUnit 10. Maybe we could add both to the README? PHPUnit 9 is still widely used so I think it would be great to have an example for 10+ as well as the versions before 10. What do you think?

**Comment by 1stthomas** [comment]
Np, then I will update the PR with PHPUnit v9 and v10 snippets. I will look into for a working example (for v9 I just have to restore your example).

**Comment by 1stthomas** [comment]
Related issue: https://github.com/sebastianbergmann/phpunit/issues/5294.

**Comment by timkrase** [comment]
Thanks for putting in the work to add both examples and making this easier to use!

**Comment by 1stthomas** [comment]
Thank you for this very usefull action!

**Pull request merged**
